run_name: mythic270m-olmo-mix-stage1
seed: 6198
dry_run: false

wandb:
  project: mythic-270m
  entity: magicsquares137
  name: ${run_name}
  group: ${run_name}
  tags: ["mythicai", "small", "pretraining"]
  log_artifacts: false
  rank_zero_only: true
  log_interval: 1000

model:
  d_model: 768
  n_heads: 12
  n_layers: 12
  # mlp_hidden_size: 22016
  mlp_ratio: 4
  weight_tying: false
  alibi: false
  rope: true
  rope_theta: 500000
  flash_attention: false
  attention_dropout: 0.0
  include_bias: false
  block_type: sequential
  layer_norm_type: rms
  layer_norm_with_affine: true
  layer_norm_eps: 1e-6
  bias_for_layer_norm: false
  attention_layer_norm: true
  attention_layer_norm_with_affine: true
  norm_after: true
  activation_type: swiglu
  residual_dropout: 0.0
  embedding_dropout: 0.0
  max_sequence_length: 4096
  vocab_size: 100278
  embedding_size: 100352
  eos_token_id: 100257
  pad_token_id: 100277
  init_device: meta
  init_fn: normal
  init_std: 0.02
  init_cutoff_factor: 3

softmax_auxiliary_loss: true
auxiliary_loss_multiplier: 1e-5
fused_loss: true

compile: null

optimizer:
  name: adamw
  learning_rate: 3.0e-4
  weight_decay: 0.1
  eps: 1e-8
  decay_norm_and_bias: true
  decay_embeddings: false
  betas:
  - 0.9
  - 0.95
  metrics_log_interval: 1

scheduler:
  name: cosine_with_warmup
  units: tokens
  t_warmup: 2000000000
  t_max: 100000000000
  alpha_f: 0.1
  warmup_min_lr: 0.0

max_duration: 2ep

tokenizer:
  identifier: allenai/OLMo-2-1124-7B
  truncate_direction: right

save_folder: /mnt/disk3/checkpoints/tests
save_overwrite: true

save_interval: null
save_interval_ephemeral: 250
save_num_checkpoints_to_keep: -1
sharded_checkpointer: olmo_core

save_interval_unsharded: 1000
save_num_unsharded_checkpoints_to_keep: -1

load_path: null

global_train_batch_size: 1023
device_train_microbatch_size: 2

precision: amp_bf16

# fsdp:
#   wrapping_strategy: by_block_and_size
#   precision: mixed

ddp:
  grad_sync_mode: batch  # or "micro_batch"
  find_unused_parameters: false

max_grad_norm: 1.0
max_grad_norm_ratio: null

speed_monitor:
  window_size: 1

gen1_gc_interval: 1

eval_interval: 1000
eval_subset_num_batches: -1
device_eval_batch_size: ${device_train_microbatch_size}
evaluators:
  ##########################
  # Downstream evaluations #
  ##########################
  - label: piqa
    type: downstream

  - label: hellaswag
    type: downstream

  - label: winogrande
    type: downstream

  - label: openbook_qa
    type: downstream

  - label: boolq
    type: downstream

  - label: sciq
    type: downstream

  - label: arc_easy
    type: downstream

  - label: arc_challenge
    type: downstream

  - label: copa
    type: downstream

  - label: commonsense_qa
    type: downstream

  - label: social_iqa
    type: downstream

  - label: mmlu_stem_var
    type: downstream

  - label: mmlu_humanities_var
    type: downstream

  - label: mmlu_social_sciences_var
    type: downstream

  - label: mmlu_other_var
    type: downstream

  - label: mmlu_stem_mc_5shot
    type: downstream

  - label: mmlu_humanities_mc_5shot
    type: downstream

  - label: mmlu_social_sciences_mc_5shot
    type: downstream

  - label: mmlu_other_mc_5shot
    type: downstream

  - label: mmlu_stem_mc_5shot_test
    type: downstream

  - label: mmlu_humanities_mc_5shot_test
    type: downstream

  - label: mmlu_social_sciences_mc_5shot_test
    type: downstream

  - label: mmlu_other_mc_5shot_test
    type: downstream

  - label: basic_arithmetic
    type: downstream

  - label: trivia_qa_wiki_ppl
    type: downstream

  - label: natural_qs_open_ppl
    type: downstream

  - label: arc_easy_ppl
    type: downstream

data:
  pad_direction: right
  # generate_doc_lengths: true
  num_workers: 16
  drop_last: true
  pin_memory: true
  prefetch_factor: 8
  persistent_workers: true
  memmap_dtype: uint16
  timeout: 0
  instance_filter:
    repetition_max_period: 13
    repetition_min_period: 1
    repetition_max_count: 32
  paths:
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00000.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00001.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00002.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00003.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00004.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00005.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00006.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00007.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00008.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00009.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00010.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00011.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00012.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00013.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00014.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00015.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00016.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00017.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00018.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00019.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00020.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00021.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00022.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00023.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00024.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00025.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00026.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00027.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00028.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00029.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00030.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00031.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00032.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00033.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00034.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00035.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00036.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00037.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00038.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00039.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00040.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00041.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00042.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00043.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00044.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00045.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00046.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00047.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00048.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00049.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00050.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00051.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00052.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00053.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00054.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00055.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00056.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00057.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00058.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00059.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00060.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00061.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00062.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00063.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00064.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00065.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00066.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00067.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00068.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00069.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00070.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00071.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00072.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00073.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00074.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00075.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00076.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00077.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00078.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00079.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00080.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00081.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00082.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00083.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00084.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00085.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00086.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00087.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00088.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00089.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00090.npy
    - /mnt/seagate/dolmino_full/npy_data/olmo-mix-npy/0_00091.npy

